apiVersion: v1
kind: Pod
metadata:
  name: repo-api-pod
spec:
  containers:
    - name: repo-api
      image: localhost/repo-api:latest
      ports:
        - containerPort: 3000
          hostPort: 3001
      healthCheck:
        command: ["curl", "-f", "http://localhost:3000/"]
        interval: 10s
        timeout: 2s
        retries: 3
